on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Add the build step here
      - name: Clear node_modules and Reinstall Dependencies
        run: |
          rm -rf node_modules
          npm install
          npm run build
        working-directory: .

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID  }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME}}
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          workingDirectory: .
          wranglerVersion: '3'
